# Generated by Django 2.0 on 2017-12-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('rescue_date', models.DateField()),
            ],
        ),
    ]
