# Generated by Django 2.0 on 2017-12-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adoption.Person'),
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccines',
            field=models.ManyToManyField(to='pet.Vaccine'),
        ),
    ]
